apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello-cronjob
              image: busybox:1.28
              command: ["sh", "-c", "date ; echo Hello from inside K8s container"]
          restartPolicy: Never
