apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret
  containers:
    - name: secret-container
      image: busybox
      command: ["sh", "-c", "env; while true; do sleep 60; done"]
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/config/secret
      env:
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: postgress_user
        - name: ADMIN_PW
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: administrator

