apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: test-container
      image: busybox
      command: [ "/bin/sh", "-c", "env; while true; do sleep 3600; done"]
      env:
        - name: CONFIG-ENV
          valueFrom:
            configMapKeyRef:
              name: configuration
              key: config.json
      envFrom:
        - configMapRef:
            name: fromenv

