apiVersion: v1
kind: PersistentVolume
metadata:
  name: delete-pv
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/tmp/delete"
