apiVersion: v1
kind: PersistentVolume
metadata:
  name: gold-sc-pv
spec:
  storageClassName: "gold-sc"
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/tmp/gold-sc"
