apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops
  namespace: devops-ns
subjects:
- kind: User
  name: devops
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: devops
  apiGroup: rbac.authorization.k8s.io
