apiVersion: v1
kind: Pod
metadata:
  name: readiness-pod
  labels:
    app: readiness
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "sleep 30; touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 60"]
    readinessProbe:
      exec:
        command: ["cat", "/tmp/healthy"]
      initialDelaySeconds: 10
      periodSeconds: 5
