apiVersion: v1
kind: Pod
metadata:
  name: startup-pod
  labels:
    app: startup-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "sleep 120"]
    startupProbe:
      exec:
        command: ["cat", "/etc/test"]
      failureThreshold: 10
      periodSeconds: 5
