apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-db
  name: user-db-lb
spec:
  externalIPs:
  - 192.168.1.100
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: user-db
  type: LoadBalancer
