apiVersion: v1
kind: Service
metadata:
  name: {{ include "myhelmchart.fullname" . }}
  labels:
    app: svc-web
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: secure-web
