apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  volumes:
    - name: config-volume
      configMap:
        name: nginx-configmap
    - name: config-index
      configMap:
        name: nginx-index-html
    - name: htpasswd-volume
      secret:
        secretName: nginx-htpasswd-secret
  containers:
  - name: nginx
    image: nginx:1.19.1
    ports:
    - containerPort: 80
    volumeMounts:
      - name: config-volume
        mountPath: /etc/nginx
      - name: config-index
        mountPath: /usr/share/nginx/html
      - name: htpasswd-volume
        mountPath: /etc/nginx/conf
