apiVersion: v1
kind: Service
metadata:
  name: {{ include "myhelmchart.fullname" . }}
  labels:
    {{- include "myhelmchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "myhelmchart.selectorLabels" . | nindent 4 }}
